- src/main/java/com/example/apoorpoor_backend/entity/AccountType.java
- src/main/java/com/example/apoorpoor_backend/entity/ChatRoom.java
- src/main/java/com/example/apoorpoor_backend/entity/FinancialLedger.java
> Feat : 가계부 Entity 추가

- build.gradle
- src/main/java/com/example/apoorpoor_backend/config/SecurityConfig.java
- src/main/java/com/example/apoorpoor_backend/controller/BeggarController.java
- src/main/java/com/example/apoorpoor_backend/controller/FinancialLedgerController.java
- src/main/java/com/example/apoorpoor_backend/dto/LedgerRequestDto.java
- src/main/java/com/example/apoorpoor_backend/dto/LedgerResponseDto.java
- src/main/java/com/example/apoorpoor_backend/model/Balance.java
- src/main/java/com/example/apoorpoor_backend/model/Beggar.java
- src/main/java/com/example/apoorpoor_backend/model/Timestamped.java
- src/main/java/com/example/apoorpoor_backend/repository/UserRepository.java
- src/main/java/com/example/apoorpoor_backend/service/FinancialLedgerService.java
스웨거 링크 : http://localhost:8080/swagger-ui/index.html#/
> Docs : Swagger 작성, 가독성을 위한 코드 주석 제거

- src/main/java/com/example/apoorpoor_backend/config/oauth/handler/OAuth2LoginSuccessHandler.java
- src/main/java/com/example/apoorpoor_backend/jwt/JwtUtil.java
- src/main/java/com/example/apoorpoor_backend/repository/BeggarRepository.java
> Feat : 소셜 로그인 성공시 Beggar캐릭터의 유무에 따른 Redirection

- src/main/java/com/example/apoorpoor_backend/config/KafkaConfig.java
- src/main/java/com/example/apoorpoor_backend/config/S3config.java
- src/main/java/com/example/apoorpoor_backend/config/WebSocketConfig.java
- src/main/java/com/example/apoorpoor_backend/controller/ChatController.java
- src/main/java/com/example/apoorpoor_backend/controller/KafkaController.java
- src/main/java/com/example/apoorpoor_backend/model/ExceptionEnum.java
- src/main/java/com/example/apoorpoor_backend/service/ChatService.java
- src/main/java/com/example/apoorpoor_backend/service/S3Uploader.java
- src/main/java/com/example/apoorpoor_backend/service/kafka/KafkaConsumer.java
- src/main/java/com/example/apoorpoor_backend/service/kafka/KafkaProducer.java
- src/test/java/com/example/apoorpoor_backend/controller/AccountControllerTest.java
> Feat: s3 이미지 업로드 기능 추가

- src/main/java/com/example/apoorpoor_backend/model/enumType/LevelType.java
- src/test/java/com/example/apoorpoor_backend/service/BeggarServiceTest.java
> Test : 테스트로 확인한 잘못된 코드 수정

- src/main/java/com/example/apoorpoor_backend/controller/BeggarController.java
- src/main/java/com/example/apoorpoor_backend/model/Badge.java
- src/main/java/com/example/apoorpoor_backend/model/GetBadge.java
- src/main/java/com/example/apoorpoor_backend/repository/GetBadgeRepository.java
- src/main/java/com/example/apoorpoor_backend/service/BeggarService.java
>  Fix : 뱃지 획득시 중간테이블에 저장 확인 및 이미 가진경우 예외 발생

- src/main/java/com/example/apoorpoor_backend/config/WebSecurityConfig.java
- src/main/java/com/example/apoorpoor_backend/controller/ShopController.java
- src/main/java/com/example/apoorpoor_backend/dto/shop/ItemListResponseDto.java
- src/main/java/com/example/apoorpoor_backend/dto/shop/ItemResponseDto.java
- src/main/java/com/example/apoorpoor_backend/model/enumType/ItemListEnum.java
- src/main/java/com/example/apoorpoor_backend/service/ShopService.java
> Fix : 상점 물품 조회 기능 정상 작동 되도록 보수

- src/main/java/com/example/apoorpoor_backend/service/BeggarService.java
> Mod : print 부분 exepction으로 변경

- .gitignore
- src/main/java/com/example/apoorpoor_backend/model/Beggar.java
- src/main/java/com/example/apoorpoor_backend/model/enumType/ItemListEnum.java
- src/main/java/com/example/apoorpoor_backend/model/enumType/UnWearEnum.java
- src/main/java/com/example/apoorpoor_backend/service/BeggarService.java
> Mod : 새로운 카테고리로 인한 아이템 조회 로직 변경

- src/main/java/com/example/apoorpoor_backend/dto/user/UserResponseDto.java
> Fix : sender Long-> String 

- .gitignore
- build.gradle
- src/main/java/com/example/apoorpoor_backend/config/FCMInit.java
- src/main/java/com/example/apoorpoor_backend/controller/FcmController.java
- src/main/java/com/example/apoorpoor_backend/controller/SseController.java
- src/main/java/com/example/apoorpoor_backend/service/BeggarService.java
- src/main/java/com/example/apoorpoor_backend/service/NotificationService.java
- src/main/resources/application-secret.yml
> Mod : sse 메시지에 뱃지 타입 추가

- src/main/java/com/example/apoorpoor_backend/config/FCMInit.java
- src/main/java/com/example/apoorpoor_backend/controller/SseController.java
- src/main/java/com/example/apoorpoor_backend/service/NotificationService.java
> Mod : jwt의 String.valueof 제거

- src/main/generated/com/example/apoorpoor_backend/model/QChat.java
- src/main/java/com/example/apoorpoor_backend/config/RedisCacheConfig.java
- src/main/java/com/example/apoorpoor_backend/config/RedisConfig.java
- src/main/java/com/example/apoorpoor_backend/controller/ChatController.java
- src/main/java/com/example/apoorpoor_backend/model/Chat.java
- src/main/java/com/example/apoorpoor_backend/service/ChatService.java
- src/main/java/com/example/apoorpoor_backend/service/LedgerHistoryService.java
- src/main/java/com/example/apoorpoor_backend/service/NotificationService.java
> Feat : 테스트용 sse 추가

- src/main/java/com/example/apoorpoor_backend/service/BeggarService.java
- src/main/java/com/example/apoorpoor_backend/service/LedgerHistoryService.java
- src/main/java/com/example/apoorpoor_backend/service/NotificationService.java
- src/test/java/com/example/apoorpoor_backend/ApoorpoorBackendApplicationTests.java
- src/test/java/com/example/apoorpoor_backend/controller/BeggarControllerTest.java
> Mod : 테스트용 SSE 알림 텍스트 변경

- src/main/java/com/example/apoorpoor_backend/service/LedgerHistoryService.java
- src/main/java/com/example/apoorpoor_backend/service/NotificationService.java
> Mod : 뱃지 획득시 SSE알림으로 수정

- build.gradle
- src/main/generated/com/example/apoorpoor_backend/dto/account/QAccountTotalResponseDto.java
- src/main/generated/com/example/apoorpoor_backend/dto/account/QMonthSumResponseDto.java
- src/main/generated/com/example/apoorpoor_backend/dto/account/QTotalSumResponseDto.java
- src/main/generated/com/example/apoorpoor_backend/dto/ledgerhistory/QLedgerHistoryResponseDto.java
- src/main/generated/com/example/apoorpoor_backend/dto/shop/QPointResponseDto.java
- src/main/generated/com/example/apoorpoor_backend/dto/social/QExpenditureAvgDto.java
- src/main/generated/com/example/apoorpoor_backend/dto/social/QExpenditureTotalDto.java
- src/main/generated/com/example/apoorpoor_backend/dto/social/QIncomeAvgDto.java
- src/main/generated/com/example/apoorpoor_backend/dto/social/QIncomeTotalDto.java
- src/main/generated/com/example/apoorpoor_backend/dto/social/QSocialResponseDto.java
- src/main/generated/com/example/apoorpoor_backend/model/QAccount.java
- src/main/generated/com/example/apoorpoor_backend/model/QBadge.java
- src/main/generated/com/example/apoorpoor_backend/model/QBalance.java
- src/main/generated/com/example/apoorpoor_backend/model/QBeggar.java
- src/main/generated/com/example/apoorpoor_backend/model/QChat.java
- src/main/generated/com/example/apoorpoor_backend/model/QFCMToken.java
- src/main/generated/com/example/apoorpoor_backend/model/QGetBadge.java
- src/main/generated/com/example/apoorpoor_backend/model/QItem.java
- src/main/generated/com/example/apoorpoor_backend/model/QLedgerHistory.java
- src/main/generated/com/example/apoorpoor_backend/model/QPoint.java
- src/main/generated/com/example/apoorpoor_backend/model/QRanking.java
- src/main/generated/com/example/apoorpoor_backend/model/QRefreshToken.java
- src/main/generated/com/example/apoorpoor_backend/model/QSocial.java
- src/main/generated/com/example/apoorpoor_backend/model/QTimestamped.java
- src/main/generated/com/example/apoorpoor_backend/model/QUser.java
- src/main/java/com/example/apoorpoor_backend/dto/beggar/BeggarCustomListResponseDto.java
- src/main/java/com/example/apoorpoor_backend/dto/beggar/BeggarCustomRequestDto.java
- src/test/java/com/example/apoorpoor_backend/controller/BeggarControllerTest.java
> Test : BeggarController Test코드 작성

- src/main/java/com/example/apoorpoor_backend/service/BeggarService.java
- src/main/java/com/example/apoorpoor_backend/service/NotificationService.java
> Feat : 레벨업시 SSE 알림 추가

- src/main/java/com/example/apoorpoor_backend/scheduler/BadgeScheduler.java
- src/main/java/com/example/apoorpoor_backend/service/BeggarService.java
- src/main/java/com/example/apoorpoor_backend/service/LedgerHistoryService.java
> Fix : 스케쥴러로 뱃지 획득시 SSE알람 나오도록 수정

- src/main/generated/com/example/apoorpoor_backend/model/QUser.java
- src/main/java/com/example/apoorpoor_backend/model/enumType/ItemListEnum.java
- src/main/java/com/example/apoorpoor_backend/service/ShopService.java
> Fix : 아이템 순서 재정렬

- src/main/java/com/example/apoorpoor_backend/model/enumType/ItemListEnum.java
> Mod : 아이템 가격 오타 수정

- src/main/java/com/example/apoorpoor_backend/service/BeggarService.java
> Fix : 닉네임에 비속어 및 성희롱 단어 포함시 닉네임 생성 방지

- src/main/java/com/example/apoorpoor_backend/service/BeggarService.java
> Mod : 닉네임 수정시 비속어 및 성적인 단어 사용 불가 기능 추가, badIdCheck 메서드를 생성하여 중복 코드 제거

- src/main/java/com/example/apoorpoor_backend/controller/BeggarController.java
- src/main/java/com/example/apoorpoor_backend/repository/beggar/BeggarRepository.java
- src/main/java/com/example/apoorpoor_backend/service/BeggarService.java
> Feat : beggar 닉네임 중복체크, 부적절한 언어 사용 여부 체크 기능 추가

- src/main/generated/com/example/apoorpoor_backend/model/QChallenge.java
- src/main/java/com/example/apoorpoor_backend/dto/challenge/ChallengeInfoResponseDto.java
- src/main/java/com/example/apoorpoor_backend/model/Challenge.java
- src/main/java/com/example/apoorpoor_backend/service/ChallengeService.java
> Mod : challenge 정보 조회 시 날짜 데이터 추가

- src/main/java/com/example/apoorpoor_backend/repository/beggar/BeggarRepository.java
- src/main/java/com/example/apoorpoor_backend/service/BeggarService.java
- src/main/resources/application-secret.yml
> Mod : Beggar 닉네임이 존재하지 않을 시 404 반환

- src/main/generated/com/example/apoorpoor_backend/model/QChat.java
- src/main/generated/com/example/apoorpoor_backend/model/QImage.java
- src/main/java/com/example/apoorpoor_backend/exception/GlobalExceptionHandler.java
- src/main/java/com/example/apoorpoor_backend/repository/challenge/ChallengeRepository.java
- src/main/java/com/example/apoorpoor_backend/service/ChallengeService.java
- src/main/resources/application-secret.yml
> Fix : 챌린지 도전이 아닐시 OK처리로 빈값 보내어 예외처리

- src/main/java/com/example/apoorpoor_backend/service/ChallengeService.java
- src/main/java/com/example/apoorpoor_backend/service/NotificationService.java
- src/main/resources/application-secret.yml
> Mod : 알람 형식 통일 및 확인용 알람 생성

- build.gradle
- src/main/java/com/example/apoorpoor_backend/dto/beggar/BeggarRequestDto.java
- src/main/java/com/example/apoorpoor_backend/service/BeggarService.java
- src/test/java/com/example/apoorpoor_backend/controller/BeggarRestControllerTest.java
- src/test/java/com/example/apoorpoor_backend/service/BeggarServiceTest.java
> Fix : 커스텀 안입혀지는 버그 수정

- src/main/java/com/example/apoorpoor_backend/model/Beggar.java
> Fix : 커스텀 착용 후 다른 아이템을 중첩해서 착용하는 버그 수정

- src/main/java/com/example/apoorpoor_backend/config/WebSecurityConfig.java
- src/main/java/com/example/apoorpoor_backend/service/BeggarService.java
- src/main/java/com/example/apoorpoor_backend/service/ChallengeService.java
- src/main/java/com/example/apoorpoor_backend/service/NotificationService.java
- src/main/java/com/example/apoorpoor_backend/service/ShopService.java
> Mod : 시험용 SSE 제거, myBeggar에 @Transactional(readOnly = true) 추가

- src/main/java/com/example/apoorpoor_backend/dto/challenge/ChallengeLedgerDto.java
- src/main/java/com/example/apoorpoor_backend/service/ChallengeService.java
> Fix : 챌린지 도전시 가계부 내역 날짜 기준 오류 수정

- src/main/java/com/example/apoorpoor_backend/dto/challenge/ChallengeLedgerDto.java
- src/main/java/com/example/apoorpoor_backend/service/ChallengeService.java
> Mod : challenge 시작시 가계부 내역 날짜 재수정

- src/main/java/com/example/apoorpoor_backend/service/ChallengeService.java
> Mod : challenge 가계부 내역 날짜 범위 조건 수정
